apiVersion: v1
kind: Namespace
metadata:
  name: hydra-proxy

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: hydra-proxy-sa
  namespace: hydra-proxy

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hydra-proxy-role
rules:
  - apiGroups: [""]
    resources: [ "*" ]
    verbs: [ "*" ]
    #resources: ["pods"]
    #verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hydra-proxy-role-binding
subjects:
  - kind: ServiceAccount
    name: hydra-proxy-sa
    namespace: hydra-proxy
roleRef:
  kind: ClusterRole
  name: hydra-proxy-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hydra-proxy
  namespace: hydra-proxy
  labels:
    app: hydra-proxy
spec:
  revisionHistoryLimit: 5
  replicas: 2
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: hydra-proxy
  template:
    metadata:
      labels:
        app: hydra-proxy
    spec:
      serviceAccountName: hydra-proxy-sa
      hostNetwork: false
      terminationGracePeriodSeconds: 100
      containers:
        - name: hydra-proxy
          image: hydra-proxy
          ports:
            - containerPort: 9988
          readinessProbe:
            httpGet:
              path: /_hydra/health
              port: 9988
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /_hydra/health
              port: 9988
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          env:
            - name: SELF_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SELF_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      securityContext:
        runAsNonRoot: true
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - hydra-proxy
                topologyKey: kubernetes.io/hostname
