apiVersion: v1
kind: Namespace
metadata:
  name: web

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-sa
  namespace: web

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: web-role
rules:
  - apiGroups: [""]
    resources: [ "*" ]
    verbs: [ "*" ]
    #resources: ["pods"]
    #verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: web-role-binding
subjects:
  - kind: ServiceAccount
    name: web-sa
    namespace: web
roleRef:
  kind: ClusterRole
  name: web-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-client
  namespace: web
  labels:
    app: example-client
spec:
  revisionHistoryLimit: 5
  replicas: 2
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: example-client
  template:
    metadata:
      labels:
        app: example-client
    spec:
      serviceAccountName: web-sa
      hostNetwork: false
      terminationGracePeriodSeconds: 100
      containers:
        - name: example-client
          image: example-client
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          env:
            - name: SELF_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SELF_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      securityContext:
        runAsNonRoot: true
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname
